CREATE SEQUENCE CARD_REQUEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE card_requests (
    id          NUMBER(19) PRIMARY KEY,
    owner_id    NUMBER NOT NULL,
    status      VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    reason      VARCHAR2(255),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_card_requests_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_request_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);
