FROM eclipse-temurin:21-jdk AS dev

RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pom.xml ./
COPY mvnw ./
COPY .mvn ./.mvn

RUN mvn dependency:go-offline -B

COPY src ./src

EXPOSE 3000

ENV MAVEN_OPTS="-Dspring-boot.run.profiles=dev"


